#!/bin/bash

if [ "$1" == "init" ]; then
  cd ./tools/wave &&\
  python -m venv venv &&\
  source venv/bin/activate &&\
  pip install -r requirements.txt
else
  cd ./tools/wave &&\
  source venv/bin/activate &&\
  python wave-cli.py $@
fi
