#!/bin/bash

if [ "$1" == "init" ]; then
  virtualenv --python=$(which python) venv &&\
  source venv/bin/activate &&\
  pip install -r requirements.txt
elif [ "$1" == "start" ]; then
  source ./venv/bin/activate &&\
  python ./wpt serve
fi
